// priority: 0

// Visit the wiki for more info - https://kubejs.com/

console.info('THE ***NETHER*** IS SUPPOSED TO BE ***HOT***')

ServerEvents.tags('worldgen/biome', event =>{
    event.removeAllTagsFrom('pyrellium:frostburn_valley')
})

ServerEvents.tags('block', event => {
    event.add('supplementaries:brick_breakable_recurisive', '#chipped:glass')
    event.add('supplementaries:brick_breakable_recurisive', '#chipped:glass_pane')
    event.add('fh:phasing', '#c:end_stones')
    event.add('fh:phasing', '#c:end_stones')
    event.add('fh:phasing', 'betterend:dense_snow')
    event.add('fh:phasing', 'betterend:emerald_ice')
    event.add('fh:phasing', 'betterend:dense_emerald_ice')
    event.add('fh:phasing', '#c:nether_stones')
    event.add('fh:phasing', 'betterend:emerald_ice')
    event.add('fh:phasing', 'pyrellium:burning_nylium')
    event.add('fh:phasing', 'betterend:emerald_ice')
    event.add('fh:phasing', '#c:nether_terrain')
    event.add('fh:phasing', 'pyrellium:netherrack_mycelium')
    event.add('fh:phasing', '#c:dirt')
    event.add('fh:phasing', '#c:stone')
    event.add('fh:phasing', '#c:deepslate')
    event.add('fh:phasing', 'minecraft:mud')
    event.add('fh:phasing', 'minecraft:clay')
    event.add('fh:phasing', '#c:ores')
    event.add('fh:phasing', 'spelunkery:rough_emerald_block')
    event.add('fh:phasing', 'spelunkery:rough_diamond_block')
    event.add('fh:phasing', 'minecraft:raw_copper_block')
    event.add('fh:phasing', 'minecraft:raw_iron_block')
    event.add('fh:phasing', 'minecraft:raw_gold_block')
    event.add('fh:phasing', 'spelunkery:rough_quartz_block')
    event.add('fh:phasing', 'minecraft:moss_block')
    event.add('fh:phasing', 'spelunkery:nephrite')
    event.add('fh:phasing', '#c:sculk_like')
    event.add('fh:phasing', 'minecraft:calcite')
    event.add('fh:phasing', 'minecraft:smooth_basalt')
    event.add('fh:phasing', 'minecraft:basalt')
    event.add('fh:phasing', 'twigs:schist')
    event.add('fh:phasing', 'twigs:rhyolite')
    event.add('fh:phasing', 'spelunkery:rock_salt_block')
    event.add('fh:phasing', 'spelunkery:salt_block')
    event.add('fh:phasing', '#minecraft:sand')
    event.add('fh:phasing', '#minecraft:snow')
    event.add('fh:phasing', 'minecraft:prismarine')
    event.add('fh:phasing', 'minecraft:dripstone_block')
    event.add('fh:phasing', '#c:ice_blocks')
    event.add('fh:phasing', '#minecraft:dirt')
})

